Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using DataLayer.Models;
using RentUpWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RentUpWeb.Constants;

namespace RentUpWeb.Controllers
{
    [Route("[controller]/[action]")]
    public class AuthenticationController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AuthenticationController(ApplicationDbContext context) => _context = context;

        [HttpGet]
        [Route("~/Authentication/SignIn")]
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        [Route("~/Authentication/SignIn")]
        public IActionResult SignIn(EmployeeSignIn employeeSignIn)
        {
            if(ModelState.IsValid)
            {
                var employee = _context.Employee.FirstOrDefault(e => e.EmployeeEmail == employeeSignIn.EmployeeEmail);

                if (employee != null)
                {
                    if (employee.EmployeeStateID != EmployeeStates.WORKING && employee.EmployeeStateID != EmployeeStates.TO_BE_FIRED)
                    {
                        ModelState.AddModelError("EmployeeEmail", "You don`t work here anymore");
                        return View(employeeSignIn);
                    }
                    if (employee.EmployeePassword == employeeSignIn.EmployeePassword)
                    {
                        TempData["RegisteredEmployee"] = employee.EmployeeEmail;
                        TempData["EmployeeState"] = employee.EmployeeStateID;
                        TempData["DepartmentID"] = employee.DepartmentID;

                        if (employee.EmployeeTypeID == EmployeeTypes.AGENT)
                            return RedirectToAction("AgentMainMenu", "Agent");
                        else if (employee.EmployeeTypeID == EmployeeTypes.MANAGER)
                            return RedirectToAction("ManagerMainMenu", "Manager");
                        else if (employee.EmployeeTypeID == EmployeeTypes.ADMIN)
                            return RedirectToAction("AdminMainMenu", "Admin");
                    }
                    else
                    {
                        ModelState.AddModelError("EmployeePassword", "Password is incorrect");
                        return View(employeeSignIn);
                    }          
                }

                ModelState.AddModelError("EmployeeEmail", "Such employee isn`t exist");
                return View(employeeSignIn);
            }
            return View();
        }
    }
}

Views/Authentication/SignIn.cshtml
@model RentUpWeb.ViewModels.EmployeeSignIn

<br />
<h2 align="center">Enter your credentials to start work</h2>
<form method="post" asp-controller="Authentication" asp-action="SignIn">
    <hr />
    <br />
    <div asp-validation-summary="ModelOnly"></div>
    <div class="form-group">
        <label asp-for="EmployeeEmail">Email</label>
        <input asp-for="EmployeeEmail" type="email" class="form-control" aria-describedby="emailHelp">
        <span asp-validation-for="EmployeeEmail" style="color:red"></span>
    </div>
    <div class="form-group">
        <label asp-for="EmployeePassword">Password</label>
        <input asp-for="EmployeePassword" type="password" class="form-control">
        <span asp-validation-for="EmployeePassword" style="color:red"></span>
    </div>
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <button type="submit" class="btn btn-success">Sign In</button>
            </div>
        </div>
    </div>
</form>