Controllers/AdminController.cs
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using RentUpWeb.ViewModels;
using RentUpWeb.Constants;

namespace RentUpWeb.Controllers
{
    [Route("[controller]/[action]")]
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AdminController(ApplicationDbContext context) => _context = context;

        [HttpGet]
        [Route("~/Admin/AdminMainMenu")]
        public IActionResult AdminMainMenu()
        {
            return View();
        }

        [HttpGet]
        [Route("~/Admin/Statistics")]
        public IActionResult Statistics()
        {
            DateTime dateForStatistic = DateTime.Now.AddMonths(-1);
            Statistics statistics = new Statistics();

            statistics.Payments = _context.Payment.Where(p => p.PaymentDate >= dateForStatistic).ToList();
            statistics.Contracts = _context.Contract.Where(c => c.SignedDate >= dateForStatistic)
                                                    .Select(c => new ContractToList()
                                                    {
                                                        ContractID = c.ContractID,
                                                        ClientEmail = c.ClientEmail,
                                                        OwnerEmail = c.Space.OwnerEmail
                                                    }).ToList();
            statistics.TotalIncome = _context.Contract.Select(c => c.OwnerPayment).Sum();
            statistics.TotalOutcome = _context.Payment.Where(p => p.ContractID == null)
                                                      .Select(p => p.PaymentSum).Sum();
            statistics.CompanyBalance = _context.Employee.FirstOrDefault(e => e.EmployeeTypeID == EmployeeTypes.ADMIN)
                                                         .EmployeeSum!;
            statistics.Profit = statistics.TotalIncome - statistics.TotalOutcome;
            statistics.WorkingEmployees = _context.Employee.Where(e => e.EmployeeStateID == EmployeeStates.WORKING).Count();
            statistics.RetiredEmployees = _context.Employee.Where(e => e.EmployeeStateID == EmployeeStates.RETIRING).Count();
            statistics.ToBeFiredEmployees = _context.Employee.Where(e => e.EmployeeStateID == EmployeeStates.TO_BE_FIRED).Count();
            statistics.FiredEmployees = _context.Employee.Where(e => e.EmployeeStateID == EmployeeStates.FIRIRNG).Count();
            statistics.SpacesCount = _context.Space.Count();
            statistics.OwnersCount = _context.Owner.Count();
            statistics.ClientsCount = _context.Client.Count();
            statistics.CitiesCount = _context.City.Count();

            return View(statistics);
        }
    }
}

Controllers/AgentController.cs
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using RentUpWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentUpWeb.Controllers
{
    [Route("[controller]/[action]")]
    public class AgentController : Controller
    {
        private readonly ApplicationDbContext _context;
        public AgentController(ApplicationDbContext context) => _context = context;

        [HttpGet]
        [Route("~/Agent/AgentMainMenu")]
        public IActionResult AgentMainMenu()
        {
            return View();
        }

        [HttpGet]
        [Route("~/Agent/Rate/{email}")]
        public IActionResult Rate(string email)
        {
            var employee = _context.Employee.FirstOrDefault(e => e.EmployeeEmail == email);
            if (employee != null)
            {
                var employeeRate = new EmployeeRate() 
                { 
                    EmployeeEmail = employee.EmployeeEmail, 
                    EmployeeName = employee.EmployeeName, 
                    EmployeeSurname = employee.EmployeeSurname,
                    EmployeeTypeName = employee.EmployeeType.EmployeeTypeName,
                    DepartmentEmail = employee.Department.DepartmentEmail,
                    ContractPercent = employee.EmployeePercent,
                    ContractSum = employee.EmployeeSum,
                    ContractNumber = employee.EmployeeContractCount
                };

                return View("AgentRate", employeeRate);
            }

            return BadRequest();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RentUpWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RentUpWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult HelpAgent()
        {
            return View();
        }

        public IActionResult HelpManager()
        {
            return View();
        }

        public IActionResult HelpAdmin()
        {
            return View();
        }

        public IActionResult Help()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ManagerController.cs
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using RentUpWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentUpWeb.Controllers
{
    [Route("[controller]/[action]")]
    public class ManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ManagerController(ApplicationDbContext context) => _context = context;

        [HttpGet]
        [Route("~/Manager/ManagerMainMenu")]
        public IActionResult ManagerMainMenu()
        {
            return View();
        }

        [HttpGet]
        [Route("~/Manager/Rate/{email}")]
        public IActionResult Rate(string email)
        {
            var employee = _context.Employee.FirstOrDefault(e => e.EmployeeEmail == email);
            if (employee != null)
            {
                var employeeRate = new EmployeeRate()
                {
                    EmployeeEmail = employee.EmployeeEmail,
                    EmployeeName = employee.EmployeeName,
                    EmployeeSurname = employee.EmployeeSurname,
                    EmployeeTypeName = employee.EmployeeType.EmployeeTypeName,
                    DepartmentEmail = employee.Department.DepartmentEmail,
                    ContractPercent = employee.EmployeePercent,
                    ContractSum = employee.EmployeeSum,
                    ContractNumber = employee.EmployeeContractCount
                };

                return View("ManagerRate", employeeRate);
            }

            return BadRequest();
        }
    }
}

Views/Home/Help.cshtml
<div class="container">
    <div class="row justify-content-center">
        <h2>RentUp</h2>
        
    </div>
</div>
<br />
<h3>About Us</h3>
<p>
    RentUp is the platform for renting spaces. You can work with us on manager or agent position. After starting work
    like agent you can get promoted to manager. <br />
    Manager`s responsibility: <br />
    - set salary for employees <br />
    - manage owners <br />
    - manage clients <br />
    - manage buildings <br />
    - manage spaces <br />
    Agent`s responsibility: <br />
    - add contracts <br />
    - manage contracts <br />
</p>

Views/Home/HelpAdmin.cshtml
<div class="container">
    <div class="row justify-content-center">
        <h2>Admin corner</h2>
    </div>
</div>

<h3>Employees</h3>
<p>
   You can view list of employees, promote agent or demote manager.
</p>
<br />
<h3>Statistics</h3>
<p>
    Statistics page is for watching info about last contracts and payment. In bottom of page admin can view 
    count of spaces, employees, clients or owners. Enjoy your work.
</p>
<br />
<form asp-action="AdminMainMenu" asp-controller="Admin" method="get">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <button class="btn btn-success">Back to Menu</button>
            </div>
        </div>
    </div>
</form>

Views/Home/HelpAgent.cshtml
<div class="container">
    <div class="row justify-content-center">
        <h2>Agent corner</h2>
    </div>
</div>

<h3>Start</h3>
<p>
    Hello here!<br />
    You have a chance to work with our team. We hope you will enjoy this time. Please follow our rules and build your
    own career with us.
</p>
<br />
<h3>My rate</h3>
<p>
    Click "My rate" to view your position, count of contracts and sum of money. All contracts will be add to your rating
    after successfull signing.
</p>
<br />
<h3>Contracts</h3>
<p>
    Contracts page helps you watch list of contracts. You can also create new contract, view details about previous work.
</p>
<br />
<form asp-action="AgentMainMenu" asp-controller="Agent" method="get">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <button class="btn btn-success">Back to Menu</button>
            </div>
        </div>
    </div>
</form>

Views/Home/HelpManager.cshtml
<div class="container">
    <div class="row justify-content-center">
        <h2>Manager corner</h2>
    </div>
</div>

<h3>Start</h3>
<p>
    Hello here!<br />
    You have a chance to work with our team. We hope you will enjoy this time. Please follow our rules and build your
    own career with us.
</p>
<br />
<h3>My rate</h3>
<p>
    Click "My rate" to view your position, count of contracts and sum of money. All contracts will be add to your rating
    after successfull signing.
</p>
<br />
<h3>Employees</h3>
<p>
    Workers list for you. Carefully manage employees from your department. You can pay salary, fire existing employee or
    hire new one. Have changings with your collegues? - Click "Edit" button to edit workers. "Datails" - for viewing info,
    "Pay salary" - to share money with others, "Fire" - if employee do not manage to do they tasks.
</p>
<br />
<h3>Clients</h3>
<p>
    Do we have any clients? - Yes. Clients page helps you to watch info about our customers. You can also edit information
    about them or remove from list but with one condition - there must be no contracts with this client.
</p>
<br />
<h3>Owners</h3>
<p>
    Owners provides space to rent to our clients. Functionality is the same like with clients (edit or remove).
</p>
<br />
<h3>Buildings</h3>
<p>
    It is the central entity that contains spaces. Select city, street and house number to add new building.
</p>
<br />
<h3>Spaces</h3>
<p>
    Don`t forget about spaces. Owners have it and clients rent it. Agents will have a chance to sign new contracts with new 
    spaces.
</p>
<br />
<form asp-action="ManagerMainMenu" asp-controller="Manager" method="get">
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <button class="btn btn-success">Back to Menu</button>
            </div>
        </div>
    </div>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>